# Generated by Django 3.2.4 on 2021-06-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('address', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='uploads/')),
            ],
        ),
    ]
