# Generated by Django 3.2.4 on 2021-06-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210612_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='studentregister',
            table='studentRegister',
        ),
    ]
