# Generated by Django 3.2.4 on 2021-06-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210613_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
